//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareX.ScreenCaptureLib.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShareX.ScreenCaptureLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_circle {
            get {
                object obj = ResourceManager.GetObject("arrow_circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_circle_135_left {
            get {
                object obj = ResourceManager.GetObject("arrow_circle_135_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_circle_225_left {
            get {
                object obj = ResourceManager.GetObject("arrow_circle_225_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_circle_double {
            get {
                object obj = ResourceManager.GetObject("arrow_circle_double", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap balloon_box_left {
            get {
                object obj = ResourceManager.GetObject("balloon_box_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Region capture.
        /// </summary>
        internal static string BaseRegionForm_InitializeComponent_Region_capture {
            get {
                return ResourceManager.GetString("BaseRegionForm_InitializeComponent_Region_capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap camera {
            get {
                object obj = ResourceManager.GetObject("camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CircleNode {
            get {
                object obj = ResourceManager.GetObject("CircleNode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clipboard {
            get {
                object obj = ResourceManager.GetObject("clipboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] closedhand {
            get {
                object obj = ResourceManager.GetObject("closedhand", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close (Esc).
        /// </summary>
        internal static string CloseEsc {
            get {
                return ResourceManager.GetString("CloseEsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap control {
            get {
                object obj = ResourceManager.GetObject("control", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap counter_reset {
            get {
                object obj = ResourceManager.GetObject("counter_reset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] Crosshair {
            get {
                object obj = ResourceManager.GetObject("Crosshair", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cursor {
            get {
                object obj = ResourceManager.GetObject("cursor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disk_black {
            get {
                object obj = ResourceManager.GetObject("disk_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disks_black {
            get {
                object obj = ResourceManager.GetObject("disks_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap drive_globe {
            get {
                object obj = ResourceManager.GetObject("drive_globe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drop shadow color....
        /// </summary>
        internal static string DropShadowColor {
            get {
                return ResourceManager.GetString("DropShadowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_alignment {
            get {
                object obj = ResourceManager.GetObject("edit_alignment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_alignment_center {
            get {
                object obj = ResourceManager.GetObject("edit_alignment_center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_alignment_center_white {
            get {
                object obj = ResourceManager.GetObject("edit_alignment_center_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_alignment_right {
            get {
                object obj = ResourceManager.GetObject("edit_alignment_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_alignment_right_white {
            get {
                object obj = ResourceManager.GetObject("edit_alignment_right_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_alignment_white {
            get {
                object obj = ResourceManager.GetObject("edit_alignment_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_bold {
            get {
                object obj = ResourceManager.GetObject("edit_bold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_bold_white {
            get {
                object obj = ResourceManager.GetObject("edit_bold_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_italic {
            get {
                object obj = ResourceManager.GetObject("edit_italic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_italic_white {
            get {
                object obj = ResourceManager.GetObject("edit_italic_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_outline {
            get {
                object obj = ResourceManager.GetObject("edit_outline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_outline_white {
            get {
                object obj = ResourceManager.GetObject("edit_outline_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_shade {
            get {
                object obj = ResourceManager.GetObject("edit_shade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_shade_white {
            get {
                object obj = ResourceManager.GetObject("edit_shade_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_underline {
            get {
                object obj = ResourceManager.GetObject("edit_underline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_underline_white {
            get {
                object obj = ResourceManager.GetObject("edit_underline_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_vertical_alignment {
            get {
                object obj = ResourceManager.GetObject("edit_vertical_alignment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_vertical_alignment_middle {
            get {
                object obj = ResourceManager.GetObject("edit_vertical_alignment_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_vertical_alignment_middle_white {
            get {
                object obj = ResourceManager.GetObject("edit_vertical_alignment_middle_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_vertical_alignment_top {
            get {
                object obj = ResourceManager.GetObject("edit_vertical_alignment_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_vertical_alignment_top_white {
            get {
                object obj = ResourceManager.GetObject("edit_vertical_alignment_top_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_vertical_alignment_white {
            get {
                object obj = ResourceManager.GetObject("edit_vertical_alignment_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clipboard does not contain an image..
        /// </summary>
        internal static string EditorStartupForm_ClipboardDoesNotContainAnImage {
            get {
                return ResourceManager.GetString("EditorStartupForm_ClipboardDoesNotContainAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eraser {
            get {
                object obj = ResourceManager.GetObject("eraser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exclamation_button {
            get {
                object obj = ResourceManager.GetObject("exclamation_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse for ffmpeg.exe.
        /// </summary>
        internal static string FFmpegOptionsForm_buttonFFmpegBrowse_Click_Browse_for_ffmpeg_exe {
            get {
                return ResourceManager.GetString("FFmpegOptionsForm_buttonFFmpegBrowse_Click_Browse_for_ffmpeg_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download of FFmpeg failed..
        /// </summary>
        internal static string FFmpegOptionsForm_DownloaderForm_InstallRequested_Download_of_FFmpeg_failed_ {
            get {
                return ResourceManager.GetString("FFmpegOptionsForm_DownloaderForm_InstallRequested_Download_of_FFmpeg_failed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Successfully downloaded FFmpeg..
        /// </summary>
        internal static string FFmpegOptionsForm_DownloaderForm_InstallRequested_Successfully_downloaded_FFmpeg_ {
            get {
                return ResourceManager.GetString("FFmpegOptionsForm_DownloaderForm_InstallRequested_Successfully_downloaded_FFmpeg_" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bitrate: {0}k.
        /// </summary>
        internal static string FFmpegOptionsForm_UpdateUI_Bitrate___0_k {
            get {
                return ResourceManager.GetString("FFmpegOptionsForm_UpdateUI_Bitrate___0_k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quality:.
        /// </summary>
        internal static string FFmpegOptionsForm_UpdateUI_Quality_ {
            get {
                return ResourceManager.GetString("FFmpegOptionsForm_UpdateUI_Quality_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_open_image {
            get {
                object obj = ResourceManager.GetObject("folder_open_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gear {
            get {
                object obj = ResourceManager.GetObject("gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gradient {
            get {
                object obj = ResourceManager.GetObject("gradient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grid {
            get {
                object obj = ResourceManager.GetObject("grid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grid_white {
            get {
                object obj = ResourceManager.GetObject("grid_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap highlighter_text {
            get {
                object obj = ResourceManager.GetObject("highlighter_text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image__pencil {
            get {
                object obj = ResourceManager.GetObject("image__pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image__plus {
            get {
                object obj = ResourceManager.GetObject("image__plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_crop {
            get {
                object obj = ResourceManager.GetObject("image_crop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_empty {
            get {
                object obj = ResourceManager.GetObject("image_empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_resize {
            get {
                object obj = ResourceManager.GetObject("image_resize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_resize_actual {
            get {
                object obj = ResourceManager.GetObject("image_resize_actual", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_saturation {
            get {
                object obj = ResourceManager.GetObject("image_saturation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_select {
            get {
                object obj = ResourceManager.GetObject("image_select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add image effects....
        /// </summary>
        internal static string ImageEffects {
            get {
                return ResourceManager.GetString("ImageEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer {
            get {
                object obj = ResourceManager.GetObject("layer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer__minus {
            get {
                object obj = ResourceManager.GetObject("layer__minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer__pencil {
            get {
                object obj = ResourceManager.GetObject("layer__pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer_flip {
            get {
                object obj = ResourceManager.GetObject("layer_flip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer_flip_vertical {
            get {
                object obj = ResourceManager.GetObject("layer_flip_vertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer_fullscreen {
            get {
                object obj = ResourceManager.GetObject("layer_fullscreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer_shade {
            get {
                object obj = ResourceManager.GetObject("layer_shade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer_shade_white {
            get {
                object obj = ResourceManager.GetObject("layer_shade_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer_shape {
            get {
                object obj = ResourceManager.GetObject("layer_shape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer_shape_arrow {
            get {
                object obj = ResourceManager.GetObject("layer_shape_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer_shape_arrow_white {
            get {
                object obj = ResourceManager.GetObject("layer_shape_arrow_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer_shape_ellipse {
            get {
                object obj = ResourceManager.GetObject("layer_shape_ellipse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer_shape_ellipse_region {
            get {
                object obj = ResourceManager.GetObject("layer_shape_ellipse_region", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer_shape_line {
            get {
                object obj = ResourceManager.GetObject("layer_shape_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer_shape_line_white {
            get {
                object obj = ResourceManager.GetObject("layer_shape_line_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer_shape_polygon {
            get {
                object obj = ResourceManager.GetObject("layer_shape_polygon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer_shape_region {
            get {
                object obj = ResourceManager.GetObject("layer_shape_region", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer_shape_round {
            get {
                object obj = ResourceManager.GetObject("layer_shape_round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer_shape_round_region {
            get {
                object obj = ResourceManager.GetObject("layer_shape_round_region", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer_shape_text {
            get {
                object obj = ResourceManager.GetObject("layer_shape_text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layers {
            get {
                object obj = ResourceManager.GetObject("layers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layers_arrange {
            get {
                object obj = ResourceManager.GetObject("layers_arrange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layers_arrange_back {
            get {
                object obj = ResourceManager.GetObject("layers_arrange_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layers_stack_arrange {
            get {
                object obj = ResourceManager.GetObject("layers_stack_arrange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layers_stack_arrange_back {
            get {
                object obj = ResourceManager.GetObject("layers_stack_arrange_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layout_center {
            get {
                object obj = ResourceManager.GetObject("layout_center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layout_split {
            get {
                object obj = ResourceManager.GetObject("layout_split", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layout_split_vertical {
            get {
                object obj = ResourceManager.GetObject("layout_split_vertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use light resize nodes.
        /// </summary>
        internal static string LightResizeNodes {
            get {
                return ResourceManager.GetString("LightResizeNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap magnifier_zoom {
            get {
                object obj = ResourceManager.GetObject("magnifier_zoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Magnify strength:.
        /// </summary>
        internal static string MagnifyStrength {
            get {
                return ResourceManager.GetString("MagnifyStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap monitor {
            get {
                object obj = ResourceManager.GetObject("monitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap monitor_image {
            get {
                object obj = ResourceManager.GetObject("monitor_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap monitor_window {
            get {
                object obj = ResourceManager.GetObject("monitor_window", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] openhand {
            get {
                object obj = ResourceManager.GetObject("openhand", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open keybinds web page....
        /// </summary>
        internal static string OpenKeybindsPage {
            get {
                return ResourceManager.GetString("OpenKeybindsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pencil {
            get {
                object obj = ResourceManager.GetObject("pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printer {
            get {
                object obj = ResourceManager.GetObject("printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rectangle capture light.
        /// </summary>
        internal static string RectangleLight_InitializeComponent_Rectangle_capture_light {
            get {
                return ResourceManager.GetString("RectangleLight_InitializeComponent_Rectangle_capture_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à X: {0} Y: {1} W: {2} H: {3}.
        /// </summary>
        internal static string RectangleRegion_GetAreaText_Area {
            get {
                return ResourceManager.GetString("RectangleRegion_GetAreaText_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RGB: {0}, {1}, {2}
        ///Hex: {3}
        ///X: {4} Y: {5}.
        /// </summary>
        internal static string RectangleRegion_GetColorPickerText {
            get {
                return ResourceManager.GetString("RectangleRegion_GetColorPickerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à X: {0} / Y: {1} / X2: {2} / Y2: {3}
        ///Width: {4} px / Height: {5} px
        ///Distance: {6:0.00} px / Angle: {7:0.00}°.
        /// </summary>
        internal static string RectangleRegion_GetRulerText_Ruler_info {
            get {
                return ResourceManager.GetString("RectangleRegion_GetRulerText_Ruler_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rectangle capture transparent.
        /// </summary>
        internal static string RectangleTransparent_RectangleTransparent_Rectangle_capture_transparent {
            get {
                return ResourceManager.GetString("RectangleTransparent_RectangleTransparent_Rectangle_capture_transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image editor.
        /// </summary>
        internal static string RegionCaptureForm_InitializeComponent_ImageEditor {
            get {
                return ResourceManager.GetString("RegionCaptureForm_InitializeComponent_ImageEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ShareX - Image editor.
        /// </summary>
        internal static string RegionCaptureForm_ShowExitConfirmation_ShareXImageEditor {
            get {
                return ResourceManager.GetString("RegionCaptureForm_ShowExitConfirmation_ShareXImageEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There are unsaved changes.
        ///Would you like to close image editor?.
        /// </summary>
        internal static string RegionCaptureForm_ShowExitConfirmation_Text {
            get {
                return ResourceManager.GetString("RegionCaptureForm_ShowExitConfirmation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tip: You can pan image by holding mouse middle button and dragging..
        /// </summary>
        internal static string RegionCaptureForm_TipYouCanPanImageByHoldingMouseMiddleButtonAndDragging {
            get {
                return ResourceManager.GetString("RegionCaptureForm_TipYouCanPanImageByHoldingMouseMiddleButtonAndDragging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop capture.
        /// </summary>
        internal static string ScrollingCaptureForm_StartCapture_Stop_capture {
            get {
                return ResourceManager.GetString("ScrollingCaptureForm_StartCapture_Stop_capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start capture.
        /// </summary>
        internal static string ScrollingCaptureForm_StopCapture_Start_capture {
            get {
                return ResourceManager.GetString("ScrollingCaptureForm_StopCapture_Start_capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrows on both ends.
        /// </summary>
        internal static string ShapeManager_ArrowsOnBothEnds {
            get {
                return ResourceManager.GetString("ShapeManager_ArrowsOnBothEnds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Center points:.
        /// </summary>
        internal static string ShapeManager_CenterPoints {
            get {
                return ResourceManager.GetString("ShapeManager_CenterPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blur strength:.
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Blur_radius_ {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Blur_radius_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Border color....
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Border_color___ {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Border_color___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Border size:.
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Border_size_ {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Border_size_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Capture.
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Capture {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Capture active monitor.
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Capture_active_monitor {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Capture_active_monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Capture fullscreen.
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Capture_fullscreen {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Capture_fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Capture monitor.
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Capture_monitor {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Capture_monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Corner radius:.
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Corner_radius_ {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Corner_radius_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable animations.
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_EnableAnimations {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_EnableAnimations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fill color....
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Fill_color___ {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Fill_color___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fixed size region mode.
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Fixed_size_region_mode {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Fixed_size_region_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Height:.
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Height_ {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Height_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Highlight color....
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Highlight_color___ {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Highlight_color___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Magnifier pixel count:.
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Magnifier_pixel_count_ {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Magnifier_pixel_count_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Magnifier pixel size:.
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Magnifier_pixel_size_ {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Magnifier_pixel_size_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Multi region mode.
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Multi_region_mode {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Multi_region_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Options {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pixel size:.
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Pixel_size_ {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Pixel_size_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remember menu state.
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_RememberMenuState {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_RememberMenuState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show FPS.
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Show_FPS {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Show_FPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show magnifier.
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Show_magnifier {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Show_magnifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show position and size info.
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Show_position_and_size_info {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Show_position_and_size_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show screen wide crosshair.
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Show_screen_wide_crosshair {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Show_screen_wide_crosshair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Square shape magnifier.
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Square_shape_magnifier {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Square_shape_magnifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Switch to drawing tool after shape selection.
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_SwitchToDrawingToolAfterSelection {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_SwitchToDrawingToolAfterSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Switch to selection tool after shape drawing.
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_SwitchToSelectionToolAfterDrawing {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_SwitchToSelectionToolAfterDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Width:.
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Width_ {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Width_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annotate menu.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_AnnotateMenu {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_AnnotateMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apply changes &amp; continue task (Enter).
        /// </summary>
        internal static string ShapeManager_CreateToolbar_ApplyChangesContinueTaskEnter {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_ApplyChangesContinueTaskEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auto close editor on task.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_AutoCloseEditorOnTask {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_AutoCloseEditorOnTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auto crop image....
        /// </summary>
        internal static string ShapeManager_CreateToolbar_AutoCropImage {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_AutoCropImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bring forward.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_BringForward {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_BringForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bring to front.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_BringToFront {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_BringToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel task (Esc).
        /// </summary>
        internal static string ShapeManager_CreateToolbar_CancelTaskEsc {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_CancelTaskEsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Canvas size....
        /// </summary>
        internal static string ShapeManager_CreateToolbar_CanvasSize {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_CanvasSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Capture regions.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_CaptureRegions {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_CaptureRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Continue task (Space or right click).
        /// </summary>
        internal static string ShapeManager_CreateToolbar_ContinueTaskSpaceOrRightClick {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_ContinueTaskSpaceOrRightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy image to clipboard (Ctrl + Shift + C).
        /// </summary>
        internal static string ShapeManager_CreateToolbar_CopyImageToClipboard {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_CopyImageToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Crop image....
        /// </summary>
        internal static string ShapeManager_CreateToolbar_CropImage {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_CropImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_Delete {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete all.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_DeleteAll {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drop shadow.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_DropShadow {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_DropShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_Edit {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editor start mode:.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_EditorStartMode {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_EditorStartMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flip horizontal.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_FlipHorizontal {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_FlipHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flip vertical.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_FlipVertical {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_FlipVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Font size:.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_FontSize {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_Image {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image size....
        /// </summary>
        internal static string ShapeManager_CreateToolbar_ImageSize {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_ImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert image file....
        /// </summary>
        internal static string ShapeManager_CreateToolbar_InsertImageFile {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_InsertImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert image from screen....
        /// </summary>
        internal static string ShapeManager_CreateToolbar_InsertImageFromScreen {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_InsertImageFromScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Interpolation mode:.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_InterpolationMode {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_InterpolationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Capture last region.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_LastRegion {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_LastRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New image....
        /// </summary>
        internal static string ShapeManager_CreateToolbar_NewImage {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_NewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open image file....
        /// </summary>
        internal static string ShapeManager_CreateToolbar_OpenImageFile {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_OpenImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paste image/text.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_PasteImageText {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_PasteImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print image... (Ctrl + P).
        /// </summary>
        internal static string ShapeManager_CreateToolbar_PrintImage {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_PrintImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rotate 180°.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_Rotate180 {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_Rotate180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rotate 90° clockwise.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_Rotate90Clockwise {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_Rotate90Clockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rotate 90° counter clockwise.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_Rotate90CounterClockwise {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_Rotate90CounterClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run after capture tasks (Enter).
        /// </summary>
        internal static string ShapeManager_CreateToolbar_RunAfterCaptureTasks {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_RunAfterCaptureTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save image (Ctrl + S).
        /// </summary>
        internal static string ShapeManager_CreateToolbar_SaveImage {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_SaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save image as... (Ctrl + Shift + S).
        /// </summary>
        internal static string ShapeManager_CreateToolbar_SaveImageAs {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_SaveImageAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send backward.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_SendBackward {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_SendBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send to back.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_SendToBack {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_SendToBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shape options.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_ShapeOptions {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_ShapeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Value of first step:.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_StartingStepValue {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_StartingStepValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Undo.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_Undo {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Upload image (Ctrl + U).
        /// </summary>
        internal static string ShapeManager_CreateToolbar_UploadImage {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use letters.
        /// </summary>
        internal static string ShapeManager_CreateToolbar_UseLetters {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_UseLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cursor type:.
        /// </summary>
        internal static string ShapeManager_CursorType {
            get {
                return ResourceManager.GetString("ShapeManager_CursorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smiley_cool {
            get {
                object obj = ResourceManager.GetObject("smiley_cool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smiley_yell {
            get {
                object obj = ResourceManager.GetObject("smiley_yell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stamp_cursor {
            get {
                object obj = ResourceManager.GetObject("stamp_cursor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap test_32 {
            get {
                object obj = ResourceManager.GetObject("test_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This window will close before opening the keybinds web page. Do you want to continue?.
        /// </summary>
        internal static string ThisWindowWillCloseBeforeOpeningKeybindsPageWantContinue {
            get {
                return ResourceManager.GetString("ThisWindowWillCloseBeforeOpeningKeybindsPageWantContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tick {
            get {
                object obj = ResourceManager.GetObject("tick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_radio_button_uncheck {
            get {
                object obj = ResourceManager.GetObject("ui_radio_button_uncheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Capture.
        /// </summary>
        internal static string WebpageCaptureForm_UpdateControls_Capture {
            get {
                return ResourceManager.GetString("WebpageCaptureForm_UpdateControls_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop.
        /// </summary>
        internal static string WebpageCaptureForm_UpdateControls_Stop {
            get {
                return ResourceManager.GetString("WebpageCaptureForm_UpdateControls_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wrench_screwdriver {
            get {
                object obj = ResourceManager.GetObject("wrench_screwdriver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
